services/views.py
# encoding=utf-8

from flask import request, flash, Blueprint, render_template, redirect, url_for, jsonify, current_app as app
from flask_login import login_required, current_user
from flaskweb.app import db
from auth.views import check_user_login
from .models import SurveyInfo, Post, Application, Profile, Idea_Post, Idea_Comments, Seminars
from .forms import SurveyForm, ProfileForm, IdeaForm, PostForm, SeminarForm
import os
from werkzeug.utils import secure_filename

basedir = os.path.dirname(__file__)
UPLOAD_FOLDER = os.path.join(basedir, "../uploads")
ALLOWED_EXTENSIONS = {'pdf', 'docx', 'doc'}

bp = Blueprint('main', __name__,
               static_url_path="/static",
               static_folder=os.path.join(basedir, "../static"),
               template_folder=os.path.join(basedir, "../templates"))


@bp.route('/', methods=['GET', 'POST'])
def index():
    # post
    form = SurveyForm()
    if form.validate_on_submit():
        email = form.email.data
        # sent to database
        app.logger.info(email)
        survey = SurveyInfo(email=form.email.data,
                            interests=form.interests.data, year=form.year.data)
        db.session.add(survey)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('index.html', form=form)


# -------------- pricing ----------------------
@bp.route('/pricing', methods=['GET'])
def pricing():
    """
    This route shows the pricing page
    :return:
    """
    return render_template('pricing.html')


# -------------- post ----------------------
@bp.route('/posts', methods=['GET'])
# @login_required
def posts():
    """
    This route shows all posts
    :return:
    """
    page = request.args.get('page', 1, type=int)
    # posts = Post.query.order_by(Post.timestamp.desc()).paginate(
    #     page, app.config['POSTS_PER_PAGE'], False)
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, 6, False)
    app.logger.info('Num of posts: ' + str(posts.total))

    next_url = url_for('main.posts', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.posts', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('posts.html', title='Explore',
                           posts=posts.items, next_url=next_url,
                           prev_url=prev_url)


@bp.route('/posts/<post_id>', methods=['GET', 'POST'])
# @login_required
def post_detail(post_id):
    """
    This route shows position detail
    :return:
    """
    # get post by post_id
    post = Post.query.filter_by(id=post_id).first_or_404()
    return render_template('_post.html', post=post)


@bp.route('/edit/post', methods=["GET", "POST"])
def edit_post():
    """
    enable this after enable auth
    :return:
    """
    form = PostForm()
    if form.validate_on_submit():
        postform = Post(lab=form.lab.data,
                        position=form.position.data,
                        details=form.details.data,
                        requirements=form.requirements.data,
                        img_addr=form.img_addr.data,
                        key_words=form.key_words.data)
        db.session.add(postform)
        db.session.commit()
        return redirect(url_for('main.edit_post'))
    return render_template('edit_post.html', form=form)


# -------------- login ----------------------


# @bp.route('/user')
# @login_required
# def user():
#     return 'hello world %s' % current_user.username


# @bp.route("/api/login", methods=["POST"])
# def login():
#     # rewrite login api
#     data = request.get_json()
#     username = data.get("username")
#     password = data.get("password")
#     if check_user_login(username, password):
#         return redirect(url_for("index"))
#     else:
#         return "login error", 400

# -------------- upload ----------------------

# @login_required
@bp.route('/api/upload', methods=["POST"])
def upload_file():
    """
    Api for uploading resume
    :return: json
    """
    # check if the post request has the file part
    if 'file' not in request.files:
        flash('No file part')
    file = request.files['file']
    post_id = request.form.to_dict()['post_id']

    # if user does not select file, browser also
    # submit an empty part without filename
    if file.filename == '':
        flash('No selected file')
    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        if not os.path.exists(UPLOAD_FOLDER):
            os.makedirs(UPLOAD_FOLDER)
        resume_addr = os.path.join(UPLOAD_FOLDER, filename)
        file.save(resume_addr)
        app.logger.info('Resume saved to ' + resume_addr)

        # save each application to the db
        application = Application(post_id=post_id,
                                  resume_addr=resume_addr)
        db.session.add(application)
        db.session.commit()

        # todo: send email after sending application
        # ref: https://www.twilio.com/blog/2018/03/send-email-programmatically-with-gmail-python-and-flask.html

        # todo: fea/enable download after uploading
        # using restful api
    return jsonify({"code": 0, "fileName": "/api/download/" + file.filename})


def allowed_file(filename):
    """
    If the file is of the acceptable extension
    :param filename: The file name to be checked
    :return:
    """
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


# -------------- Profile ----------------------
@bp.route('/edit/profile', methods=["GET", "POST"])
def profile():
    """
    enable this after enable auth
    :return:
    """
    form = ProfileForm()
    if form.validate_on_submit():
        profile = Profile(email=form.email.data,
                          name=form.name.data,
                          major=form.major.data,
                          education=form.education.data,
                          year=form.year.data,
                          interests=form.interests.data)
        db.session.add(profile)
        db.session.commit()
        return redirect(url_for('main.profile'))
    return render_template('profile.html', form=form)


# -------------- Plaza ----------------------
@bp.route('/plaza', methods=["GET", "POST"])
def plaza():
    """
    This is the feed
    todo: how to design pull/push model???
    todo: how to store it in db?
    pull更好实现？
    :return:
    """
    # receive text inputs
    form = IdeaForm()
    # if form.validate_on_submit():
    # todo: why the validators doesn't work
    if request.method == 'POST':
        app.logger.debug('idea received')
        app.logger.info(form.idea.data)
        idea_post = Idea_Post(body=form.idea.data)
        db.session.add(idea_post)
        db.session.commit()
        flash('Your idea is now live!')
        return redirect(url_for('main.plaza'))
    else:
        app.logger.debug('----GET----')

    page = request.args.get('page', 1, type=int)
    # posts = Post.query.order_by(Post.timestamp.desc()).paginate(
    #     page, app.config['POSTS_PER_PAGE'], False)

    # feeding by timeline
    # paginate object!!!
    idea_posts = Idea_Post.query.order_by(Idea_Post.timestamp.desc()).paginate(
        page, 10, False)
    app.logger.info('Num of idea posts: ' + str(idea_posts.total))

    next_url = url_for('main.plaza', page=idea_posts.next_num) \
        if idea_posts.has_next else None
    prev_url = url_for('main.plaza', page=idea_posts.prev_num) \
        if idea_posts.has_prev else None

    return render_template('plaza.html', title='plaza',
                           posts=idea_posts.items, next_url=next_url,
                           prev_url=prev_url, form=form)


# -------------- post ----------------------
@bp.route('/idea_detail/<idea_id>', methods=['GET'])
# @login_required
def idea_detail(idea_id):
    """
    This route shows feed detail
    todo: replies to comments
    :return:
    """
    # get post by idea_id
    idea_post = Idea_Post.query.filter_by(id=idea_id).first_or_404()
    # get comments by idea_id
    comments = Idea_Comments.query.filter_by(id=idea_id).order_by(Idea_Comments.timestamp).all()

    return render_template('idea_post.html', idea_post=idea_post, comments=comments)


# -------------- Seminar ----------------------
@bp.route('/seminars', methods=['GET'])
# @login_required
def seminars():
    """
    This route shows feed detail
    todo: replies to comments
    :return:
    """
    page = request.args.get('page', 1, type=int)
    # feeding by timeline
    # pagination object!!!
    seminars = Seminars.query \
        .order_by(Seminars.timestamp.desc()).paginate(page, 10, False)
    app.logger.info('Num of seminars: ' + str(seminars.total))

    next_url = url_for('main.seminars', page=seminars.next_num) \
        if seminars.has_next else None
    prev_url = url_for('main.seminars', page=seminars.prev_num) \
        if seminars.has_prev else None

    return render_template('seminars.html', title='Seminars',
                           posts=seminars.items,
                           next_url=next_url, prev_url=prev_url)


@bp.route('/seminars/<seminar_id>', methods=['GET'])
def seminar_detail(seminar_id):
    """
    This route shows feed detail
    todo: Profile的设计
    :return:
    """
    # get post by idea_id
    seminar = Seminars.query.filter_by(id=seminar_id).first_or_404()

    return render_template('_seminar.html', seminar=seminar)


@bp.route('/edit/seminar', methods=["GET", "POST"])
def edit_seminar():
    """
    enable this after enable auth
    :return:
    """
    form = SeminarForm()

templates/_post.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block js %}
    <script type="text/javascript">
        $(document).ready(function () {
            $("#btn_upload").click(function (event) {
                event.preventDefault();
                var form_data = new FormData($('#fileUploadForm')[0]);
                form_data.append('post_id', '{{ post.id }}');
                $.ajax({
                    type: 'POST',
                    url: '/api/upload',
                    data: form_data,
                    contentType: false,
                    cache: false,
                    processData: false,
                    success: function (response) {
                        if (response != 0) {
                            alert('file uploaded');
                        } else {
                            alert('file not uploaded');
                        }
                    },
                });
            });
        });

        window.onload = convert(1);
        window.onload = convert(2);
    </script>

{% endblock %}

{% block body %}
    <h1>{{ post.lab }}</h1>
    <h2>Position Description</h2>

    <p id="post{{ post.id }}abstract"> {{ post.position }} </p>
    <h2>Position Detail</h2>
    <p id="plain_style1" style="display: none"> {{ post.details }} </p>
    <p id="markdown_style1"></p>

    <h2>Requirements</h2>
    <p id="plain_style2" style="display: none"> {{ post.requirements }} </p>
    <p id="markdown_style2"></p>

    <h2>Upload your resume</h2>
    <form method="post" enctype="multipart/form-data" id="fileUploadForm">
        <input type="file" name="file" id="file">
        <input type="submit" value="Upload" id="btn_upload">
    </form>
{% endblock %}

templates/_seminar.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block js %}
    <script>
        window.onload = convert(1);
    </script>
{% endblock %}
{% block body %}
    <div style="text-align:center">
        <h4>{{ seminar.seminar_name }}</h4>
        <h1> {{ seminar.title }} </h1>
    </div>

    <div style="text-align:center">
        <p>{{ seminar.speaker_name }}</p>
        <p>{{ seminar.speaker_department }}</p>
        <p>{{ seminar.address }}</p>
        <p>{{ seminar.time }}</p>
    </div>

    <p>
    <p id="plain_style1" style="display: none"> {{ seminar.abstract }} </p>
    <p id="markdown_style1"></p>

    </p>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="/static/img/favicon.png" type="image/png">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    {% block meta %}
        <meta name="description" content="">
        <meta name="author" content="">
    {% endblock %}

    <!-- main css -->
    <link rel="stylesheet" href="/static/css/style.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="/static/css/vendor/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/main.css"/>


    {% block css %}

    {% endblock %}
</head>

<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('main.index') }}">ResearchLink</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('main.posts') }}">Explore</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('main.seminars') }}">Seminars</a>
        </li>
        {#        <li class="nav-item active">#}
        {#            <a class="nav-link" href="{{ url_for('main.pricing') }}">Price</a>#}
        {#        </li>#}
    </ul>
</nav>

<div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    {% block body %}
    {% endblock %}
</div>

<div class="main_container" id="id_main_container">
    <div class="container_inner" id="display_div_id">
    </div>
</div>

<script type="text/javascript" src="/static/js/vendor/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/vendor/bootstrap.min.js"></script>
<script src=" https://cdn.jsdelivr.net/npm/showdown@1.9.1/dist/showdown.min.js"></script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-156251860-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-156251860-1');
</script>
<script>
    function convert(i) {
        var converter = new showdown.Converter();
        var text = document.getElementById("plain_style" + i).innerHTML;
        {#var text = document.getElementById("markdown_style").text;#}
        var html = converter.makeHtml(text);
        document.getElementById("markdown_style" + i).innerHTML = html;
    }
</script>

{% block js %}

{% endblock %}
</body>
</html>

templates/edit_post.html
{% extends "base.html" %}

{% block title %}Post Editing{% endblock %}

{% block body %}
    <h1 class="text-center">Post Editing</h1>

    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <form role="form" action="{{ url_for('main.edit_post') }}" method="post">
                {{ form.hidden_tag() }}
                {% for f in form if f.type != 'CSRFTokenField' %}
                    <div class="form-group">
                        {{ f.label }}
                        {% if f.errors %}
                        <ul>
                            {% for e in f.errors %}
                            <li>{{ e }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        {{ f(class_="form-control") }}
                    </div>
                {% endfor %}

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
{% endblock %}

templates/explore_seminars.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/explore.css"/>
{% endblock %}

{% block body %}

    <main role="main">

        <section class="jumbotron text-center">
            <div class="container">
                <h1 class="jumbotron-heading">Find your dream lab!</h1>
                <p class="lead text-muted">Hey, these labs looking for talented researchers like you!</p>
                <!-- <p>
            <a href="#" class="btn btn-primary my-2">Main call to action</a>
            <a href="#" class="btn btn-secondary my-2">Secondary action</a>
            </p> -->
            </div>
        </section>

        <div class="album py-5 bg-light">
            <div class="container">

                <div class="row">
                    {% for post in posts %}
                        <div class="col-md-4">
                            <div class="card mb-4 box-shadow">
                                <img class="card-img-top" src="{{ post.img_addr }}"
                                     alt="lab logo">
                                <div class="card-body">
                                    <p class="card-text">{{ post.abstract }}</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a href="{{ url_for('main.position_detail', post_id=post.id) }}">
                                                <button type="button" class="btn btn-sm btn-primary">View More</button>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <nav aria-label="...">
            <ul class="pager">
                <li class="previous">
                    <a href="{{ prev_url or '#' }}">
                        <span aria-hidden="true">&larr;</span> Newer posts
                    </a>
                </li>
                <li class="next">
                    <a href="{{ next_url or '#' }}">
                        Older posts <span aria-hidden="true">&rarr;</span>
                    </a>
                </li>
            </ul>
        </nav>

    </main>

{% endblock %}

templates/idea_post.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block body %}
<h2>Question</h2>
<p id="post{{ idea_post.id }}"> {{ idea_post.body }} </p>
<h2>Upload your comments</h2>
    <form></form>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}Flask Login Example{% endblock %}

{% block body %}
    <h1 class="text-center">Flask Login Example</h1>

    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <form role="form" action="{{ url_for('.login', next=nexturl) }}" method="post">
                {{ form.hidden_tag() }}

                <div class="form-group">
                    {{ form.username.label }}
                    {% if form.username.errors %}
                        {% for e in form.username.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.username(class_="form-control") }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}
                    {% if form.password.errors %}
                        {% for e in form.password.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.password(class_="form-control") }}
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            <p>Don't have an account? <a href="{{ url_for('.register') }}">Click here to register.</a></p>
        </div>
        <div class="col-md-4"></div>
{% endblock %}

templates/post-edit.html
{% extends "base.html" %}

{% block title %}Post Editing{% endblock %}

{% block body %}
    <h1 class="text-center">Post Editing</h1>

    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <form role="form" action="{{ url_for('main.edit_post') }}" method="post">
                {{ form.hidden_tag() }}
                {% for f in form if f.type != 'CSRFTokenField' %}
                    <div class="form-group">
                        {{ f.label }}
                        {% if f.errors %}
                        <ul>
                            {% for e in f.errors %}
                            <li>{{ e }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        {{ f(class_="form-control") }}
                    </div>
                {% endfor %}

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
{% endblock %}

templates/posts.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/explore.css"/>
    <style>
        .mui-ellipsis-3 {
            display: -webkit-box;
            overflow: hidden;
        {#white-space: normal !important;#} text-overflow: ellipsis;
            word-wrap: break-word;
            -webkit-line-clamp: 2;
            -webkit-box-orient: vertical;
        }

        {#.innerCtn {#}
        {#    text-indent: 1rem;#}
        {#    line-height: 0.8rem;#}
        {#    font-size: 0.5rem;#}
        {
        #}#}
    </style>
{% endblock %}

<script type="text/javascript">
    $(function () {//显示三行 多余隐藏 点击展开
        $('.innerCtn').click(function () {
            $(this).children(0).removeClass('mui-ellipsis-3');
        });
    });
</script>


{% block body %}

    <main role="main">

        <section class="jumbotron text-center">
            <div class="container">
                <h1 class="jumbotron-heading">Find your dream lab!</h1>
                <p class="lead text-muted">Hey, these labs looking for talented researchers like you!</p>
                <!-- <p>
            <a href="#" class="btn btn-primary my-2">Main call to action</a>
            <a href="#" class="btn btn-secondary my-2">Secondary action</a>
            </p> -->
            </div>
        </section>

        <div class="album py-5 bg-light">
            <div class="container">
                <div class="row">
                    {% for post in posts %}
                        <div class="col-md-4">
                            <div class="card mb-4 box-shadow">
                                <img class="card-img-top" src="{{ post.img_addr }}"
                                     alt="lab logo">
                                <div class="card-body">
                                    <p class="card-text mui-ellipsis-3">{{ post.lab }}</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a href="{{ url_for('main.post_detail', post_id=post.id) }}">
                                                <button type="button" class="btn btn-sm btn-primary">View More</button>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <ul class="pagination justify-content-center">
            <li class="page-item {% if not prev_url %} disabled{% endif %}"><a class="page-link"
                                                                               href="{{ prev_url or '#' }}">Previous</a>
            </li>
            <li class="page-item {% if not next_url %} disabled{% endif %}"><a class="page-link"
                                                                               href="{{ next_url or '#' }}">Next</a>
            </li>
        </ul>

    </main>

{% endblock %}

templates/pricing.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/css/pricing.css" />
{% endblock %}

{% block body %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Pricing</h1>
  <p class="lead">We are currently offering free service for all researchers.</p>
</div>

<div class="container">
  <div class="card-deck mb-2 text-center">
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Free</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$0 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>Recommendation of labs and researchers</li>
          <li>Building your professional profile</li>
          <li>Sharing ideas inner/cross department</li>
          <li>Finding your potential partnar</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-primary">Sign up for free</button>
      </div>
    </div>
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Pro</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$?? <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>...</li>
          <li>How much do you want to pay for it?</li>
          <li>...</li>
          <li>...</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-outline-primary">Coming</button>
      </div>
    </div>
    <!-- <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Enterprise</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$29 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>30 users included</li>
          <li>15 GB of storage</li>
          <li>Phone and email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-primary">Contact us</button>
      </div> -->
    </div>
  </div>
</div>

{% endblock %}

templates/seminars.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/explore.css"/>
{% endblock %}

{% block body %}

    <main role="main">

        <section class="jumbotron text-center">
            <div class="container">
                <h1 class="jumbotron-heading">Explore seminar information!</h1>
                <p class="lead text-muted">Find what's going on in the campus!</p>
            </div>
        </section>

        {% for post in posts %}
            <table class="table table-hover">
                <tr width="100%">
                    <td width="20%">
                        <a href="{{ url_for('main.seminar_detail', seminar_id=post.id) }}">
                            <button type="button" class="btn btn-sm btn-outline-primary">View More</button>
                        </a>
                    </td>
                    <td width="40%">
                        <h6 class="text-left" id="{{ post.id }}">{{ post.title }}</h6>
                    </td>
                    <td width="40%">
                        <span class="text-left" id="{{ post.id }}">{{ post.speaker_name }}</span>
                    </td>
                </tr>
            </table>
        {% endfor %}

        <ul class="pagination justify-content-center">
            <li class="page-item {% if not prev_url %} disabled{% endif %}"><a class="page-link" href="{{ prev_url or '#' }}">Previous</a></li>
            <li class="page-item {% if not next_url %} disabled{% endif %}"><a class="page-link" href="{{ next_url or '#' }}">Next</a></li>
        </ul>

    </main>

{% endblock %}